--- #YAML:1.0
name:               Authen-ACE4
version:            1.3
abstract:           Access to SecurID ACE version 4 and up
author:
    - Open System Consultants, Mike McCauley (mikem@open.com.au)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
